github action try fix chrmodriver

diff --git a/.github/workflows/test_dash_app.yml b/.github/workflows/test_dash_app.yml
--- a/.github/workflows/test_dash_app.yml
+++ b/.github/workflows/test_dash_app.yml
@@ -24,12 +24,17 @@ jobs:
           wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
           sudo apt install -y ./google-chrome-stable_current_amd64.deb
 
-      - name: Install ChromeDriver
+      - name: Download and Install ChromeDriver
         run: |
-          wget -q "https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/linux64/chromedriver-linux64.zip"
-          unzip chromedriver_linux64.zip -d .
-          sudo mv chromedriver /usr/local/bin/chromedriver
-          sudo chmod +x /usr/local/bin/chromedriver
+          wget -v "https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.126/linux64/chromedriver-linux64.zip"
+          if [ -f "chromedriver_linux64.zip" ]; then
+            unzip chromedriver_linux64.zip -d .
+            sudo mv chromedriver /usr/local/bin/chromedriver
+            sudo chmod +x /usr/local/bin/chromedriver
+          else
+            echo "Failed to download ChromeDriver."
+            exit 1
+          fi
 
       - name: Install dependencies
         run: |
